### ISSUE TITLE
Home Assistant completely unresponsive when service is running

### ISSUE THREAD

**Issue by tiredjohn** [tobinbrooke/icue2mqtt#3]
A bit of a strange one, two issues:

1) I can't get the service to output any logs whatsoever, which is a bit of a problem for getting to the bottom of the second issue.
2) As soon as the service starts running, Home Assistant (on an Intel NUC) becomes completely unresponsive. I didn't think that would be possible (since all this service is supposed to be doing is sending MQTT messages to the MQTT server running on the NUC), but I've now tested it 10 times and without fail, running icue2mqtt paralyses my HA server. (And without logging, I have no idea why.) 

Any pointers on where I can start debugging this?

**Comment by tobinbrooke** [comment]
1. Because I made the stupid decision to make it create it's own event topic under the Applications and service logs group of the event viewer, it will need to run as admin the first time so that it can create it (I never got around to changing it to use the general application log to avoid this). The easiest way to get it to run as admin is simply to run it as a console application as admin the first time. After it is created, it will no longer need admin privileges.
2. This is quite perplexing. Is the NUC running home assistant the same machine the icue service is running on?

**Comment by tiredjohn** [comment]
iCUE (and icue2mqtt) is running on my desktop PC, with the NUC being a dedicated Home Assistant server. I keep testing it over and over to make sure it isn't my imagination - without fail, the second I start the service it knocks HA offline. All automations freeze up and I can't access the server over the web interface anymore. When I stop the service, HA comes back online a few minutes later. 

The logs show it's connecting to the MQTT server and publishing the devices. (And sure enough, when HA comes back online I see the entities have been discovered.)
`Starting
Connecting to MQTT broker
Connected to MQTT broker
Publishing device MM800RGB
Publishing device ST100RGB
Stopping`

**Comment by tiredjohn** [comment]
Getting closer to solving the mystery. Since running the service locks up the NUC, I set up an MQTT server locally so I could watch the logs in more detail. 

![image](https://user-images.githubusercontent.com/3694478/79680307-ef263d80-8240-11ea-9e37-4375f37878d3.png)

Basically it floods the MQTT with updates as fast as it possibly can, instead of when a value changes. Will dig into source and see if I can fix when I get a minute.

**Comment by tobinbrooke** [comment]
I have had some time to investigate this and it seems that the cause was subscribing to the state topic. Not sure why but it seems to cause HA to poll for the state again as soon as  it gets the reply. I have removed the subscription to the state topic and made it return the state on set. I believe this will resolve your issue

**Comment by CarterBrehm** [comment]
For someone who's having this same issue, can you please explain what you did in more detail? I've been having issues with my entire network as soon as I installed this and I think its because this program is flooding my network with packets. How did you "remove the subscription to the state topic"?

**Comment by tobinbrooke** [comment]
In the initial implementation, I publish the devices available along with the details of the appropriate mqtt topics, I was then subscribing to the state topic messages for each device as I was working under the understanding that home assistant would call these when it wanted to get the updated state. When a message with the state topic was received I was responding with the state of the device. From analysing the calls it seems that sending a state topic caused home assistant to send a message to the state topic which in my case was sending the state back to home assistant again and so on. This was a failure on my part in understanding of mqtt. It seems subscribing to the state topic is used to receive updates of a mqtt item in a different product not the product responsable for setting the state. To no longer subscribe to the state topic I simply removed the lines of code subscribing to them and this has fixed the CPU and network load on my home assistant machine for me. It would be good to see if this fixes it for you too. Apologies for the error

**Comment by tiredjohn** [comment]
Works perfectly now, thanks for the quick fix.
